# Numpy


In [1]:
import numpy as np

# Question 1 getting even nums from 70 to 100 

In [2]:
Even_num = np.linspace(30,70,21)

In [3]:
Even_num

array([30., 32., 34., 36., 38., 40., 42., 44., 46., 48., 50., 52., 54.,
       56., 58., 60., 62., 64., 66., 68., 70.])

# Question 2 to generate an array of 15 random numbers from a standard normal
distribution*

In [4]:
random = np.random.randn((15))

In [5]:
random

array([-0.7333272 ,  0.39596359,  1.0151679 , -2.32513028,  0.90646723,
        0.04523621,  0.35451526,  0.51735859, -1.37037916,  0.94691978,
       -0.41557958, -1.47372368,  0.58938863,  0.44439781,  0.21626961])

# Question 3 to compute the cross-product of two matrices in NumPy?

In [6]:
matrice_1 = np.array([[1,2],[3,4]])

In [7]:
matrice_2 = np.array([[1,2],[1,2]])

In [8]:
multiplication = np.multiply(matrice_1,matrice_2)

In [9]:
multiplication

array([[1, 4],
       [3, 8]])

# Question 4  to compute the determinant of an array using NumPy?

In [10]:
matrix = np.array([[1,2],[1,2]])

In [11]:
matrix

array([[1, 2],
       [1, 2]])

In [12]:
deter = np.linalg.det(matrix)

In [13]:
deter

0.0

# Question 5  to create a 3x3x3 array with random values using NumPy?

In [14]:
rand_array = np.random.randint(0,100, size=(3,3))

In [15]:
rand_array

array([[ 0, 91,  6],
       [13, 30, 56],
       [54, 80, 43]])

# Question 6 to create a 5x5 array with random values and find the minimum and maximum values using NumPy

In [16]:
random_array = np.random.randint(0,100, size=(5,5))

In [17]:
random_array

array([[50, 62, 97, 79, 95],
       [64,  5, 12, 34, 56],
       [67, 18, 15, 63, 32],
       [85, 26, 69, 24, 20],
       [39, 40, 72, 28,  1]])

In [18]:
maximum_int = np.max(random_array)

In [19]:
minimum_int = np.min(random_array)

In [20]:
maximum_int

97

In [21]:
minimum_int

1

# Question 7  to compute the mean, standard deviation, and variance of a given array along the second axis in
NumPy?

In [22]:
arrray = np.array([[1,2,3],[1,2,3],[1,2,3]])

In [23]:
arrray_mean = np.mean(arrray)

In [24]:
arrray_standard_daviation = np.std(arrray)

In [25]:
arrray_variance = np.var(arrray)

In [26]:
arrray_mean

2.0

In [27]:
arrray_standard_daviation

0.816496580927726

In [28]:
arrray_variance

0.6666666666666666

## Finish